import { createServer, defineConfig, type Plugin, type ViteDevServer } from 'vite'
import react from '@vitejs/plugin-react'

type CalEvent = { id: string }
type CalModules = {
  events: CalEvent[]
  icsContent: (e: CalEvent) => string
}

// Loads the app's own event data and calendar code through Vite, so the
// .ics files are always generated by the same code the site uses.
async function loadCalendar(server: ViteDevServer): Promise<CalModules> {
  const data = await server.ssrLoadModule('/src/data/events.ts')
  const cal = await server.ssrLoadModule('/src/lib/calendar.ts')
  return { events: data.events, icsContent: cal.icsContent }
}

// Emits one real /cal/<event-id>.ics file per event. A real file served as
// text/calendar opens the native "add event" sheet on iPhone, which a data:
// link or a download does not.
function icsFiles(): Plugin {
  return {
    name: 'ics-files',
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        const match = req.url?.match(/\/cal\/([^/?]+)\.ics(?:\?.*)?$/)
        if (!match) return next()
        try {
          const { events, icsContent } = await loadCalendar(server)
          const event = events.find((e) => e.id === decodeURIComponent(match[1]))
          if (!event) return next()
          res.setHeader('Content-Type', 'text/calendar; charset=utf-8')
          res.end(icsContent(event))
        } catch (err) {
          next(err)
        }
      })
    },
    async generateBundle() {
      const server = await createServer({
        configFile: false,
        appType: 'custom',
        server: { middlewareMode: true },
        logLevel: 'error',
      })
      try {
        const { events, icsContent } = await loadCalendar(server)
        for (const event of events) {
          this.emitFile({
            type: 'asset',
            fileName: `cal/${event.id}.ics`,
            source: icsContent(event),
          })
        }
      } finally {
        await server.close()
      }
    },
  }
}

// VITE_BASE lets the same build work at a domain root ("/") or a
// GitHub Pages sub-path ("/<repo>/"). Defaults to "/".
export default defineConfig({
  base: process.env.VITE_BASE ?? '/',
  plugins: [react(), icsFiles()],
})
