import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createServer, defineConfig, type Plugin, type ViteDevServer } from 'vite'
import react from '@vitejs/plugin-react'

type CalEvent = { id: string }
type CalModules = {
  events: CalEvent[]
  icsContent: (e: CalEvent) => string
}

// Loads the app's own event data and calendar code through Vite, so the
// .ics files are always generated by the same code the site uses.
async function loadCalendar(server: ViteDevServer): Promise<CalModules> {
  const data = await server.ssrLoadModule('/src/data/events.ts')
  const cal = await server.ssrLoadModule('/src/lib/calendar.ts')
  return { events: data.events, icsContent: cal.icsContent }
}

// Emits one real /cal/<event-id>.ics file per event. A real file served as
// text/calendar opens the native "add event" sheet on iPhone, which a data:
// link or a download does not.
function icsFiles(): Plugin {
  return {
    name: 'ics-files',
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        const match = req.url?.match(/\/cal\/([^/?]+)\.ics(?:\?.*)?$/)
        if (!match) return next()
        try {
          const { events, icsContent } = await loadCalendar(server)
          const event = events.find((e) => e.id === decodeURIComponent(match[1]))
          if (!event) return next()
          res.setHeader('Content-Type', 'text/calendar; charset=utf-8')
          res.end(icsContent(event))
        } catch (err) {
          next(err)
        }
      })
    },
    async generateBundle() {
      const server = await createServer({
        configFile: false,
        appType: 'custom',
        server: { middlewareMode: true },
        logLevel: 'error',
      })
      try {
        const { events, icsContent } = await loadCalendar(server)
        for (const event of events) {
          this.emitFile({
            type: 'asset',
            fileName: `cal/${event.id}.ics`,
            source: icsContent(event),
          })
        }
      } finally {
        await server.close()
      }
    },
  }
}

// Static hosts such as GitHub Pages only know about real files. Writing a copy
// of the app shell for every route means /events, /language and /about load
// directly with a 200 status and the right title, instead of a 404 fallback.
const routes: Record<string, string> = {
  events: 'Events · Japan Society St Andrews',
  language: 'Japanese lessons · Japan Society St Andrews',
  about: 'About · Japan Society St Andrews',
}

function routePages(): Plugin {
  let outDir = 'dist'
  return {
    name: 'route-pages',
    apply: 'build',
    configResolved(config) {
      outDir = config.build.outDir
    },
    closeBundle() {
      const shell = readFileSync(join(outDir, 'index.html'), 'utf8')
      for (const [route, title] of Object.entries(routes)) {
        const html = shell.replace(/<title>[^<]*<\/title>/, `<title>${title}</title>`)
        writeFileSync(join(outDir, `${route}.html`), html)
        mkdirSync(join(outDir, route), { recursive: true })
        writeFileSync(join(outDir, route, 'index.html'), html)
      }
      // Anything else falls back to the app, which shows its own not-found page.
      writeFileSync(join(outDir, '404.html'), shell)
    },
  }
}

// VITE_BASE lets the same build work at a domain root ("/") or a
// GitHub Pages sub-path ("/<repo>/"). Defaults to "/".
export default defineConfig({
  base: process.env.VITE_BASE ?? '/',
  plugins: [react(), icsFiles(), routePages()],
})
